# -*- coding: utf-8 -*-
"""attentionmask.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wWhc1Iik7-EybIKcPIprDQjfbBsxRpVI
"""

from google.colab import drive
drive.mount('/content/drive')
drive_path = "/content/drive/MyDrive/model_data"

pip install "git+https://github.com/SKTBrain/KoBERT.git#egg=kobert_tokenizer&subdirectory=kobert_hf"

import torch
import json
import os
from google.colab import userdata
from huggingface_hub import login
hf_token = userdata.get('HF_TOKEN')
login(token=hf_token)
from transformers import AutoModel, AutoTokenizer, BertTokenizer
from kobert_tokenizer import KoBERTTokenizer

model_name = ['monologg/kobert',
'snunlp/KR-BERT-char16424',
'klue/bert-base',
'klue/roberta-base',
'google-bert/bert-base-multilingual-cased',
]

#'monologg/kobert',
#'snunlp/KR-BERT-char16424',
#'klue/bert-base',
#'klue/roberta-base',
#'google-bert/bert-base-multilingual-cased',
#'meta-llama/Llama-3.2-3B'

target_model = model_name[0]
if target_model == r"monologg/kobert":
  tokenizer = KoBERTTokenizer.from_pretrained(target_model, trust_remote_code=True)
else:
  tokenizer = AutoTokenizer.from_pretrained(target_model)
model = AutoModel.from_pretrained(target_model,device_map="auto")
model.eval() #regularization 생략함(random성X)

input_path = "/content/drive/MyDrive/controlg.jsonl"
composite_sentence = []
separate_sentence = []
with open(input_path,'r',encoding="utf-8") as f:
    for line in f:
        data = json.loads(line)
        composite_sentence.append(data["composite_sentence"])
        separate_sentence.append(data["separate_sentence"])

inputs_composite = tokenizer(composite_sentence, padding=True, return_tensors="pt").to("cuda")
inputs_separate = tokenizer(separate_sentence, padding=True, return_tensors="pt").to("cuda")

model_name = target_model.replace("/", "_")
save_path = f"/content/drive/MyDrive/tokenizer/{model_name}_tokenizer.pt"
torch.save({"composite": inputs_composite['attention_mask'], "separate": inputs_separate["attention_mask"]} , save_path)

