# -*- coding: utf-8 -*-
"""data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HmAfUjnOZYh8srmUTv1IUWC2ZJU_FOZO
"""

from google.colab import drive
drive.mount('/content/drive')
drive_path = "/content/drive/MyDrive/model_data"

import torch

model_name = "snunlp_KR-BERT-char16424"

composite_path = f"/content/drive/MyDrive/model_data/{model_name}_composite.pt"
separate_path = f"/content/drive/MyDrive/model_data/{model_name}_separate.pt"
data_composite = torch.load(composite_path,map_location=torch.device('cpu'))
data_separate = torch.load(separate_path,map_location=torch.device('cpu'))
N = 13

print(len(data_composite[0][0,:,0]))
print(len(data_separate[0][0,:,0]))

#google-bert_bert-base-multilingual-cased
#size linenumber = 293, composite maxtoken = 185, separate maxtoken = 185, hidden dimension = 768

#klue_bert-base
#size linenumber = 293, composite maxtoken = 137, separate maxtoken = 155, hidden dimension = 768

#klue_roberta-base
#size linenumber = 293, composite maxtoken = 137, separate maxtoken = 155, hidden dimension = 768

#monologg_kobert
#size linenumber = 293, composite maxtoken = 52, separate maxtoken = 57, hidden dimension = 768

#snunlp_KR-BERT-char16424
#size linenumber = 293, composite maxtoken = 92, separate maxtoken = 98, hidden dimension = 768

import os
import torch
import numpy as np
import matplotlib.pyplot as plt

print(model_name)
folder = f"/content/drive/MyDrive/layer_analysis/{model_name}"
if not os.path.exists(folder):
    os.makedirs(folder)


def debiased_hsic(A, B):
    n = A.shape[0]
    A = A.copy()
    B = B.copy()
    np.fill_diagonal(A, 0.0)
    np.fill_diagonal(B, 0.0)
    ones = np.ones(n)
    term1 = np.trace(A @ B)
    term2 = (ones @ A @ ones) * (ones @ B @ ones) / ((n - 1) * (n - 2))
    term3 = (2.0 / (n - 2)) * (ones @ A @ B @ ones)
    return (term1 + term2 - term3) / (n * (n - 3))


def whiten_features(X, eps=1e-6):
    X = X - X.mean(axis=0, keepdims=True)
    U, S, Vt = np.linalg.svd(X, full_matrices=False)
    S_inv = 1.0 / np.sqrt(S**2 / (X.shape[0] - 1) + eps)
    return (X @ Vt.T) * S_inv @ Vt


def linear_CKA_debiased(X, Y):
    X = X - X.mean(axis=0, keepdims=True)
    Y = Y - Y.mean(axis=0, keepdims=True)
    K = X @ X.T
    L = Y @ Y.T
    hkk = debiased_hsic(K, K)
    hll = debiased_hsic(L, L)
    if hkk <= 0 or hll <= 0:
        return None
    return debiased_hsic(K, L) / np.sqrt(hkk * hll)


means = []  # 레이어마다 CKA 값

# 마스크 로드
mask_data = torch.load(
    f"/content/drive/MyDrive/tokenizer/{model_name}_tokenizer.pt",
    map_location=torch.device('cpu'),
)
mask_X = mask_data['composite'].float()  # (293, seq_len_composite)
mask_Y = mask_data['separate'].float()   # (293, seq_len_separate)

for n in range(13):
    X_raw = data_composite[n].cpu()  # (293, seq_len, 768)
    Y_raw = data_separate[n].cpu()

    mask_X_exp = mask_X.unsqueeze(-1).expand_as(X_raw)
    mask_Y_exp = mask_Y.unsqueeze(-1).expand_as(Y_raw)
    count_X = mask_X.sum(dim=1, keepdim=True).clamp(min=1e-9)
    count_Y = mask_Y.sum(dim=1, keepdim=True).clamp(min=1e-9)

    X_clean = (X_raw * mask_X_exp).sum(dim=1) / count_X
    Y_clean = (Y_raw * mask_Y_exp).sum(dim=1) / count_Y
    X_clean = X_clean.detach().numpy()
    Y_clean = Y_clean.detach().numpy()

    X_white = whiten_features(X_clean)
    Y_white = whiten_features(Y_clean)

    score = linear_CKA_debiased(X_white, Y_white)
    if score is None:
        print(f"데이터 확인 필요")
        score = float('nan')

    means.append(score)
    print(f"{n} / CKA = {means[-1]:.4f}")


plt.figure(figsize=(10, 6))
layers = np.arange(13)
means_arr = np.array(means, dtype=float)

plt.plot(layers, means_arr, color='black', marker='o', markersize=6)
plt.title("Layer-wise Debiased Linear CKA (full n=293, no bootstrap)")
plt.xlabel("Layer")
plt.ylabel("Debiased Linear CKA")
plt.xticks(layers)
plt.grid(True, linestyle='--', alpha=0.5)

filepath = f"{folder}/{model_name}_debiased_cka_graph.pdf"
plt.savefig(filepath, dpi=300, bbox_inches="tight")
plt.show()

# 결과 저장
np.savez(
    f"{folder}/{model_name}_debiased_cka_values.npz",
    layers=layers, means=means_arr,
)

