# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eNgNSNovxb6ZWxSL6L07cHp3XLuz6KJp
"""

from google.colab import drive
drive.mount('/content/drive')
drive_path = "/content/drive/MyDrive/model_data"

pip install "git+https://github.com/SKTBrain/KoBERT.git#egg=kobert_tokenizer&subdirectory=kobert_hf"

import torch
import json
import os
from google.colab import userdata
from huggingface_hub import login
hf_token = userdata.get('HF_TOKEN')
login(token=hf_token)
from transformers import AutoModel, AutoTokenizer, BertTokenizer, logging as tf_logging
from kobert_tokenizer import KoBERTTokenizer

# 허깅페이스 경고 메시지 무시 설정
tf_logging.set_verbosity_error()

model_name = ['monologg/kobert',
'snunlp/KR-BERT-char16424',
'klue/bert-base',
'klue/roberta-base',
'google-bert/bert-base-multilingual-cased',
]

#'monologg/kobert',
#'snunlp/KR-BERT-char16424',
#'klue/bert-base',
#'klue/roberta-base',
#'google-bert/bert-base-multilingual-cased',
#'meta-llama/Llama-3.2-3B'

target_model = model_name[0]
if target_model == r"monologg/kobert":
  tokenizer = KoBERTTokenizer.from_pretrained(target_model, trust_remote_code=True)
else:
  tokenizer = AutoTokenizer.from_pretrained(target_model)
model = AutoModel.from_pretrained(target_model,device_map="auto")
model.eval() #regularization 생략함(random성X)

input_path = "/content/drive/MyDrive/controlg.jsonl"
composite_sentence = []
separate_sentence = []
with open(input_path,'r',encoding="utf-8") as f:
    for line in f:
        data = json.loads(line)
        composite_sentence.append(data["composite_sentence"])
        separate_sentence.append(data["separate_sentence"])

inputs_composite = tokenizer(composite_sentence, padding=True, return_tensors="pt").to("cuda")
inputs_separate = tokenizer(separate_sentence, padding=True, return_tensors="pt").to("cuda")

with torch.no_grad():
    outputs_composite = model(**inputs_composite, output_hidden_states=True)
    outputs_separate = model(**inputs_separate, output_hidden_states=True)


save_dir = "/content/drive/MyDrive/model_data"

model_name = target_model.replace("/", "_")
save_path_composite = os.path.join(save_dir, f"{model_name}_composite.pt")
save_path_separate = os.path.join(save_dir, f"{model_name}_separate.pt")
torch.save(outputs_composite.hidden_states, save_path_composite)
torch.save(outputs_separate.hidden_states, save_path_separate)

