# -*- coding: utf-8 -*-
"""data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1epy2B2f5SSw1vfHKR7ACH9n7NTrcbpGg
"""

from google.colab import drive
drive.mount('/content/drive')
drive_path = "/content/drive/MyDrive/model_data"

import torch

model_name = "klue_roberta-base"

composite_path = f"/content/drive/MyDrive/model_data/{model_name}_composite.pt"
separate_path = f"/content/drive/MyDrive/model_data/{model_name}_separate.pt"
data_composite = torch.load(composite_path)
data_separate = torch.load(separate_path)
N = 13

print(len(data_composite[0][0,:,0]))
print(len(data_separate[0][0,:,0]))

#google-bert_bert-base-multilingual-cased
#size linenumber = 293, composite maxtoken = 161, separate maxtoken = 185, hidden dimension = 768

#klue_bert-base
#size linenumber = 293, composite maxtoken = 137, separate maxtoken = 155, hidden dimension = 768

#klue_roberta-base
#size linenumber = 293, composite maxtoken = 137, separate maxtoken = 155, hidden dimension = 768

#monologg_kobert
#size linenumber = 293, composite maxtoken = 52, separate maxtoken = 57, hidden dimension = 768

#snunlp_KR-BERT-char16424
#size linenumber = 293, composite maxtoken = 92, separate maxtoken = 98, hidden dimension = 768



#t-SNE
import sklearn as sk

n_lower = 2
model = sk.manifold.TSNE(n_components=n_lower,metric="cosine",random_state=723)
def tsne(data1,data2,i):
  data = np.vstack((data1,data2))
  embedding = model.fit_transform(data)
  return embedding

import numpy as np
import matplotlib.pyplot as plt
import os

folder = f"/content/drive/MyDrive/tsnedata/{model_name}"
for i in range(N):
  if not os.path.exists(folder):
    os.makedirs(folder)
  plt.figure(figsize=(5,5))
  input_composite = data_composite[i].detach().numpy()
  input_separate = data_separate[i].detach().numpy()

  pooled_composite = np.mean(input_composite,axis=1)
  pooled_separate = np.mean(input_separate,axis=1)

  t = tsne(pooled_composite,pooled_separate,i)

  composite = t[:293]
  separate = t[293:]
  for j in range(293):
    com = composite[j]
    sep = separate[j]
    plt.plot([com[0],sep[0]],[com[1],sep[1]], color='gray', linestyle='-', linewidth=0.5, alpha=0.4)

  plt.savefig(f"{folder}/{model_name}_{i}.pdf",dpi=300,bbox_inches='tight')

  plt.close()



#cs - 사용x
def cs(data1,data2):
  result = []
  for i in range(len(data1)):
    v1 = data1[i]
    v2 = data2[i]

    dot_product = np.dot(v1, v2)
    norm_v1 = np.linalg.norm(v1)
    norm_v2 = np.linalg.norm(v2)

    sim = dot_product / (norm_v1 * norm_v2 + 1e-8)
    result.append(sim)
  return result

import matplotlib.pyplot as plt
import os
import numpy as np
import torch.nn.functional as F

similarity = []
folder = f"/content/drive/MyDrive/layer_analysis/{model_name}"
if not os.path.exists(folder):
    os.makedirs(folder)
for i in range(N):

  input_composite = data_composite[i].detach().numpy()
  input_separate = data_separate[i].detach().numpy()

  pooled_composite = np.mean(input_composite,axis=1)
  pooled_separate = np.mean(input_separate,axis=1)

  similarity.append(cs(pooled_composite,pooled_separate))
_, ax = plt.subplots()
ax.boxplot(similarity)
ax.set_xlabel('Layer')
ax.set_ylabel('Cosine Similarity')

filepath = f"{folder}/{model_name}_csgraph.pdf"
plt.savefig(filepath,dpi=300,bbox_inches="tight")
plt.show()



#naive cka
import os
import torch
import numpy as np
import matplotlib.pyplot as plt

print(model_name)

folder = f"/content/drive/MyDrive/layer_analysis/{model_name}"
if not os.path.exists(folder):
    os.makedirs(folder)

def linear_CKA(X, Y):
    X = X - X.mean(axis=0, keepdims=True)
    Y = Y - Y.mean(axis=0, keepdims=True)

    K = X @ X.T
    L = Y @ Y.T

    def hsic(A, B):
        N = A.shape[0]
        H = np.eye(N) - (1.0 / N)
        return np.sum((H @ A @ H) * (H @ B @ H))

    hsic_kl = hsic(K, L)
    hsic_kk = hsic(K, K)
    hsic_ll = hsic(L, L)

    if hsic_kk * hsic_ll == 0:
        return 0
    return hsic_kl / np.sqrt(hsic_kk * hsic_ll)

means, stds = [], []
num_bootstraps = 30
sample_size = 100

for n in range(13):
    X_layer = data_composite[n].flatten(start_dim=1).detach().numpy()
    Y_layer = data_separate[n].flatten(start_dim=1).detach().numpy()

    layer_cka_scores = []

    for _ in range(num_bootstraps):
        indices = np.random.choice(X_layer.shape[0], size=sample_size, replace=False)

        X_sample = X_layer[indices]
        Y_sample = Y_layer[indices]

        cka_val = linear_CKA(X_sample, Y_sample)
        layer_cka_scores.append(cka_val)

    means.append(np.mean(layer_cka_scores))
    stds.append(np.std(layer_cka_scores))
    print(f"{n} / {means[-1]:.4f}")

plt.figure(figsize=(10, 6))
layers = np.arange(13)
plt.errorbar(layers,means,yerr=stds,fmt='o-',color='black',ecolor='black',elinewidth=1.5,capsize=3,markersize=6)
plt.title("Layer-wise Linear CKA (30 bootstrap) ")
plt.xlabel("Layer")
plt.ylabel("Linear CKA")
plt.xticks(layers)
plt.grid(True, linestyle='--', alpha=0.5)
filepath = f"{folder}/{model_name}_ckagraph.pdf"
plt.savefig(filepath,dpi=300,bbox_inches="tight")
plt.show()


#분산 활용한 padding 제거 naive cka
import os
import torch
import numpy as np
import matplotlib.pyplot as plt

print(model_name)

folder = f"/content/drive/MyDrive/layer_analysis/{model_name}"
if not os.path.exists(folder):
    os.makedirs(folder)

def linear_CKA(X, Y):
    X = X - X.mean(axis=0, keepdims=True)
    Y = Y - Y.mean(axis=0, keepdims=True)

    K = X @ X.T
    L = Y @ Y.T

    def hsic(A, B):
        N = A.shape[0]
        H = np.eye(N) - (1.0 / N)
        return np.sum((H @ A @ H) * (H @ B @ H))

    hsic_kl = hsic(K, L)
    hsic_kk = hsic(K, K)
    hsic_ll = hsic(L, L)

    if hsic_kk * hsic_ll == 0:
        return 0
    return hsic_kl / np.sqrt(hsic_kk * hsic_ll)


means, stds = [], []
num_bootstraps = 30
sample_size = 100

for n in range(13):
    X_raw = data_composite[n].cpu() if torch.is_tensor(data_composite[n]) else torch.tensor(data_composite[n])
    Y_raw = data_separate[n].cpu() if torch.is_tensor(data_separate[n]) else torch.tensor(data_separate[n])

    mask_X = (X_raw.var(dim=0).mean(dim=-1) > 1e-5).float() # 구조: [Seq_Len] (진짜단어=1, 패딩=0)
    mask_Y = (Y_raw.var(dim=0).mean(dim=-1) > 1e-5).float() # 구조: [Seq_Len]

    mask_X_expanded = mask_X.unsqueeze(0).unsqueeze(-1).expand_as(X_raw)
    mask_Y_expanded = mask_Y.unsqueeze(0).unsqueeze(-1).expand_as(Y_raw)

    X_clean = (X_raw * mask_X_expanded).sum(dim=1) / torch.clamp(mask_X.sum(), min=1e-9)
    Y_clean = (Y_raw * mask_Y_expanded).sum(dim=1) / torch.clamp(mask_Y.sum(), min=1e-9)

    X_clean = X_clean.detach().numpy()
    Y_clean = Y_clean.detach().numpy()

    layer_cka_scores = []

    for _ in range(num_bootstraps):
        indices = np.random.choice(X_clean.shape[0], size=sample_size, replace=False)

        X_sample = X_clean[indices]
        Y_sample = Y_clean[indices]

        cka_val = linear_CKA(X_sample, Y_sample)
        layer_cka_scores.append(cka_val)

    means.append(np.mean(layer_cka_scores))
    stds.append(np.std(layer_cka_scores))
    print(f"{n} / {means[-1]:.4f}")

plt.figure(figsize=(10, 6))
layers = np.arange(13)
plt.errorbar(layers,means,yerr=stds,fmt='o-',color='black',ecolor='black',elinewidth=1.5,capsize=3,markersize=6)
plt.title("Layer-wise Linear CKA (30 bootstrap) ")
plt.xlabel("Layer")
plt.ylabel("Linear CKA")
plt.xticks(layers)
plt.grid(True, linestyle='--', alpha=0.5)
filepath = f"{folder}/{model_name}_ckagraph1.pdf"
plt.savefig(filepath,dpi=300,bbox_inches="tight")
plt.show()


#attention mask로 padding 제거 naive cka
import os
import torch
import numpy as np
import matplotlib.pyplot as plt

print(model_name)

folder = f"/content/drive/MyDrive/layer_analysis/{model_name}"
if not os.path.exists(folder):
    os.makedirs(folder)

def linear_CKA(X, Y):
    X = X - X.mean(axis=0, keepdims=True)
    Y = Y - Y.mean(axis=0, keepdims=True)

    K = X @ X.T
    L = Y @ Y.T

    def hsic(A, B):
        N = A.shape[0]
        H = np.eye(N) - (1.0 / N)
        return np.sum((H @ A @ H) * (H @ B @ H))

    hsic_kl = hsic(K, L)
    hsic_kk = hsic(K, K)
    hsic_ll = hsic(L, L)

    if hsic_kk * hsic_ll == 0:
        return 0
    return hsic_kl / np.sqrt(hsic_kk * hsic_ll)


means, stds = [], []
num_bootstraps = 30
sample_size = 100

# 마스크 로드

mask_data = torch.load(f"/content/drive/MyDrive/tokenizer/{model_name}_tokenizer.pt",map_location=torch.device('cpu'))

mask_X = mask_data['composite'].float()  # (293, seq_len_composite)

mask_Y = mask_data['separate'].float()   # (293, seq_len_separate)

for n in range(13):

    X_raw = data_composite[n].cpu()  # (293, seq_len, 768)

    Y_raw = data_separate[n].cpu()

    # 문장별 마스크 확장 (293, seq_len, 1)

    mask_X_exp = mask_X.unsqueeze(-1).expand_as(X_raw)

    mask_Y_exp = mask_Y.unsqueeze(-1).expand_as(Y_raw)

    # 문장별 실제 토큰 수 (293, 1)

    count_X = mask_X.sum(dim=1, keepdim=True).clamp(min=1e-9)

    count_Y = mask_Y.sum(dim=1, keepdim=True).clamp(min=1e-9)

    # masked mean pooling → (293, 768)

    X_clean = (X_raw * mask_X_exp).sum(dim=1) / count_X

    Y_clean = (Y_raw * mask_Y_exp).sum(dim=1) / count_Y

    X_clean = X_clean.detach().numpy()

    Y_clean = Y_clean.detach().numpy()

    # ---- 이하 부트스트랩 및 CKA 연산 부분은 기존 연구자님 코드와 동일 ----
    layer_cka_scores = []

    for _ in range(num_bootstraps):
        indices = np.random.choice(X_clean.shape[0], size=sample_size, replace=False)

        X_sample = X_clean[indices]
        Y_sample = Y_clean[indices]

        cka_val = linear_CKA(X_sample, Y_sample)
        layer_cka_scores.append(cka_val)

    means.append(np.mean(layer_cka_scores))
    stds.append(np.std(layer_cka_scores))
    print(f"{n} / {means[-1]:.4f}")

plt.figure(figsize=(10, 6))
layers = np.arange(13)
plt.errorbar(layers,means,yerr=stds,fmt='o-',color='black',ecolor='black',elinewidth=1.5,capsize=3,markersize=6)
plt.title("Layer-wise Linear CKA (30 bootstrap) ")
plt.xlabel("Layer")
plt.ylabel("Linear CKA")
plt.xticks(layers)
plt.grid(True, linestyle='--', alpha=0.5)
filepath = f"{folder}/{model_name}_ckagraph2.pdf"
plt.savefig(filepath,dpi=300,bbox_inches="tight")
plt.show()


#naive cka 통한 부트스트랩 -> Two-way ANOVA
import os
import torch
import numpy as np
import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols

# ANOVA 분석용
anova_rows = []

print(model_name)

folder = f"/content/drive/MyDrive/bootstrap"
if not os.path.exists(folder):
    os.makedirs(folder)

def linear_CKA(X, Y):
    X = X - X.mean(axis=0, keepdims=True)
    Y = Y - Y.mean(axis=0, keepdims=True)

    K = X @ X.T
    L = Y @ Y.T

    def hsic(A, B):
        N = A.shape[0]
        H = np.eye(N) - (1.0 / N)
        return np.sum((H @ A @ H) * (H @ B @ H))

    hsic_kl = hsic(K, L)
    hsic_kk = hsic(K, K)
    hsic_ll = hsic(L, L)

    if hsic_kk * hsic_ll == 0:
        return 0
    return hsic_kl / np.sqrt(hsic_kk * hsic_ll)


means, stds = [], []
num_bootstraps = 30
sample_size = 100

# 마스크 로드

mask_data = torch.load(f"/content/drive/MyDrive/tokenizer/{model_name}_tokenizer.pt",map_location=torch.device('cpu'))

mask_X = mask_data['composite'].float()  # (293, seq_len_composite)

mask_Y = mask_data['separate'].float()   # (293, seq_len_separate)

for n in range(13):

    X_raw = data_composite[n].cpu()  # (293, seq_len, 768)

    Y_raw = data_separate[n].cpu()

    # 문장별 마스크 확장 (293, seq_len, 1)

    mask_X_exp = mask_X.unsqueeze(-1).expand_as(X_raw)

    mask_Y_exp = mask_Y.unsqueeze(-1).expand_as(Y_raw)

    # 문장별 실제 토큰 수 (293, 1)

    count_X = mask_X.sum(dim=1, keepdim=True).clamp(min=1e-9)

    count_Y = mask_Y.sum(dim=1, keepdim=True).clamp(min=1e-9)

    # masked mean pooling → (293, 768)

    X_clean = (X_raw * mask_X_exp).sum(dim=1) / count_X

    Y_clean = (Y_raw * mask_Y_exp).sum(dim=1) / count_Y

    X_clean = X_clean.detach().numpy()

    Y_clean = Y_clean.detach().numpy()

    # ---- 이하 부트스트랩 및 CKA 연산 부분은 기존 연구자님 코드와 동일 ----
    layer_cka_scores = []

    for _ in range(num_bootstraps):
        indices = np.random.choice(X_clean.shape[0], size=sample_size, replace=False)

        X_sample = X_clean[indices]
        Y_sample = Y_clean[indices]

        cka_val = linear_CKA(X_sample, Y_sample)
        layer_cka_scores.append(cka_val)

        anova_rows.append({
            'Group': 'Original',
            'Layer': n,
            'CKA': cka_val
        })

df_orig = pd.DataFrame(anova_rows)
df_orig.to_csv(f'{folder}/{model_name}_bootstrap.csv', index=False)

