# -*- coding: utf-8 -*-
"""shuffle_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tuUgsnBKuCj8H8Jbj-RC0NrNPMaD3w_J
"""

from google.colab import drive
drive.mount('/content/drive')
drive_path = "/content/drive/MyDrive/model_data"

import numpy as np
import torch
import json
import os
from google.colab import userdata
from huggingface_hub import login
hf_token = userdata.get('HF_TOKEN')
login(token=hf_token)
from transformers import AutoModel, AutoTokenizer, BertTokenizer, logging as tf_logging

# 허깅페이스 경고 메시지 무시 설정
tf_logging.set_verbosity_error()

model = ['monologg/kobert',
'snunlp/KR-BERT-char16424',
'klue/bert-base',
'klue/roberta-base',
'google-bert/bert-base-multilingual-cased',
]


#'monologg/kobert',
#'snunlp/KR-BERT-char16424',
#'klue/bert-base',
#'klue/roberta-base',
#'google-bert/bert-base-multilingual-cased',
#'meta-llama/Llama-3.2-3B'

target_model = model[0]
model_name = target_model.replace("/", "_")
#tokenizer = AutoTokenizer.from_pretrained(target_model)
tokenizer = BertTokenizer.from_pretrained(target_model, use_fast=False)
model = AutoModel.from_pretrained(target_model,device_map="auto")
model.eval() #regularization 생략함(random성X)

input_path = "/content/drive/MyDrive/batch_processed2.jsonl"
composite_sentence = []
separate_sentence = []
with open(input_path,'r',encoding="utf-8") as f:
    for line in f:
        data = json.loads(line)
        composite_sentence.append(data["composite_sentence"])
        separate_sentence.append(data["separate_sentence"])

inputs_composite = tokenizer(composite_sentence, padding=True, return_tensors="pt").to("cuda")
inputs_separate = tokenizer(separate_sentence, padding=True, return_tensors="pt").to("cuda")

save_path = f"/content/drive/MyDrive/tokenizer/{model_name}_tokenizer.pt"
torch.save({"composite": inputs_composite['attention_mask'], "separate": inputs_separate["attention_mask"]} , save_path)


#shuffle
rng = np.random.default_rng(seed=42)

input_ids_batch = inputs_separate["input_ids"].clone().cpu()
attn_batch = inputs_separate["attention_mask"].clone().cpu()

shuffled_input_ids_list = []

for input_ids, attn_mask in zip(input_ids_batch, attn_batch):
    special_mask = tokenizer.get_special_tokens_mask(
        input_ids.tolist(), already_has_special_tokens=True
    )

    content_positions = [
        i for i, (m, a) in enumerate(zip(special_mask, attn_mask.tolist()))
        if m == 0 and a == 1
    ]

    shuffled_positions = content_positions.copy()
    rng.shuffle(shuffled_positions)

    new_input_ids = input_ids.clone()
    new_input_ids[content_positions] = input_ids[shuffled_positions]

    shuffled_input_ids_list.append(new_input_ids)

inputs_separate = {
    "input_ids": torch.stack(shuffled_input_ids_list).to("cuda"),
    "attention_mask": inputs_separate["attention_mask"].to("cuda")
}


with torch.no_grad():
    outputs_composite = model(**inputs_composite, output_hidden_states=True)
    outputs_separate = model(**inputs_separate, output_hidden_states=True)


save_dir = "/content/drive/MyDrive/model_data"

model_name = target_model.replace("/", "_")
save_path_composite = os.path.join(save_dir, f"{model_name}_composite.pt")
save_path_separate = os.path.join(save_dir, f"{model_name}_separate.pt")
torch.save(outputs_composite.hidden_states, save_path_composite)
torch.save(outputs_separate.hidden_states, save_path_separate)







import torch

model_name = "google-bert_bert-base-multilingual-cased"

composite_path = f"/content/drive/MyDrive/model_data/{model_name}_composite.pt"
separate_path = f"/content/drive/MyDrive/model_data/{model_name}_separate.pt"
data_composite = torch.load(composite_path,map_location=torch.device('cpu'))
data_separate = torch.load(separate_path,map_location=torch.device('cpu'))
N = 13

print(len(data_composite[0][0,:,0]))
print(len(data_separate[0][0,:,0]))

#google-bert_bert-base-multilingual-cased
#size linenumber = 293, composite maxtoken = 161, separate maxtoken = 161, hidden dimension = 768

#klue_bert-base
#size linenumber = 293, composite maxtoken = 137, separate maxtoken = 137, hidden dimension = 768

#klue_roberta-base
#size linenumber = 293, composite maxtoken = 137, separate maxtoken = 137, hidden dimension = 768

#monologg_kobert
#size linenumber = 293, composite maxtoken = 52, separate maxtoken = 57, hidden dimension = 768

#snunlp_KR-BERT-char16424
#size linenumber = 293, composite maxtoken = 92, separate maxtoken = 92, hidden dimension = 768





#debiased cka
import os
import torch
import numpy as np
import matplotlib.pyplot as plt

print(model_name)
folder = f"/content/drive/MyDrive/layer_analysis/{model_name}"
if not os.path.exists(folder):
    os.makedirs(folder)


def debiased_hsic(A, B):
    n = A.shape[0]
    A = A.copy()
    B = B.copy()
    np.fill_diagonal(A, 0.0)
    np.fill_diagonal(B, 0.0)
    ones = np.ones(n)
    term1 = np.trace(A @ B)
    term2 = (ones @ A @ ones) * (ones @ B @ ones) / ((n - 1) * (n - 2))
    term3 = (2.0 / (n - 2)) * (ones @ A @ B @ ones)
    return (term1 + term2 - term3) / (n * (n - 3))


def whiten_features(X, eps=1e-6):
    X = X - X.mean(axis=0, keepdims=True)
    U, S, Vt = np.linalg.svd(X, full_matrices=False)
    S_inv = 1.0 / np.sqrt(S**2 / (X.shape[0] - 1) + eps)
    return (X @ Vt.T) * S_inv @ Vt


def linear_CKA_debiased(X, Y):
    X = X - X.mean(axis=0, keepdims=True)
    Y = Y - Y.mean(axis=0, keepdims=True)
    K = X @ X.T
    L = Y @ Y.T
    hkk = debiased_hsic(K, K)
    hll = debiased_hsic(L, L)
    if hkk <= 0 or hll <= 0:
        return None
    return debiased_hsic(K, L) / np.sqrt(hkk * hll)


means = []  # 레이어마다 CKA 값

# 마스크 로드
mask_data = torch.load(
    f"/content/drive/MyDrive/tokenizer/{model_name}_tokenizer.pt",
    map_location=torch.device('cpu'),
)
mask_X = mask_data['composite'].float()
mask_Y = mask_data['separate'].float()

for n in range(13):
    X_raw = data_composite[n].cpu()  # (293, seq_len, 768)
    Y_raw = data_separate[n].cpu()

    mask_X_exp = mask_X.unsqueeze(-1).expand_as(X_raw)
    mask_Y_exp = mask_Y.unsqueeze(-1).expand_as(Y_raw)
    count_X = mask_X.sum(dim=1, keepdim=True).clamp(min=1e-9)
    count_Y = mask_Y.sum(dim=1, keepdim=True).clamp(min=1e-9)

    X_clean = (X_raw * mask_X_exp).sum(dim=1) / count_X
    Y_clean = (Y_raw * mask_Y_exp).sum(dim=1) / count_Y
    X_clean = X_clean.detach().numpy()
    Y_clean = Y_clean.detach().numpy()

    X_white = whiten_features(X_clean)
    Y_white = whiten_features(Y_clean)

    score = linear_CKA_debiased(X_white, Y_white)
    if score is None:
        print(f"데이터 확인 필요")
        score = float('nan')

    means.append(score)
    print(f"{n} / CKA = {means[-1]:.4f}")


plt.figure(figsize=(10, 6))
layers = np.arange(13)
means_arr = np.array(means, dtype=float)

plt.plot(layers, means_arr, color='black', marker='o', markersize=6)
plt.title("Layer-wise Debiased Linear CKA (full n=293, no bootstrap)")
plt.xlabel("Layer")
plt.ylabel("Debiased Linear CKA")
plt.xticks(layers)
plt.grid(True, linestyle='--', alpha=0.5)

filepath = f"{folder}/{model_name}_debiased_cka_graph.pdf"
plt.savefig(filepath, dpi=300, bbox_inches="tight")
plt.show()

#결과 저장
np.savez(
    f"{folder}/{model_name}_debiased_cka_values.npz",
    layers=layers, means=means_arr,
)


#t-SNE
import sklearn as sk

n_lower = 2
model = sk.manifold.TSNE(n_components=n_lower,metric="cosine",random_state=723)
def tsne(data1,data2,i):
  data = np.vstack((data1,data2))
  embedding = model.fit_transform(data)
  return embedding

import numpy as np
import matplotlib.pyplot as plt
import os

folder = f"/content/drive/MyDrive/tsnedata/{model_name}"
for i in range(N):
  if not os.path.exists(folder):
    os.makedirs(folder)
  plt.figure(figsize=(5,5))
  input_composite = data_composite[i].detach().numpy()
  input_separate = data_separate[i].detach().numpy()

  pooled_composite = np.mean(input_composite,axis=1)
  pooled_separate = np.mean(input_separate,axis=1)

  t = tsne(pooled_composite,pooled_separate,i)

  composite = t[:293]
  separate = t[293:]
  for j in range(293):
    com = composite[j]
    sep = separate[j]
    plt.plot([com[0],sep[0]],[com[1],sep[1]], color='gray', linestyle='-', linewidth=0.5, alpha=0.4)

  plt.savefig(f"{folder}/{model_name}_{i}.pdf",dpi=300,bbox_inches='tight')

  plt.close()

